#!/usr/bin/perl
# Fake typing with sfx, display input file as if being typed.
# In text, > starts 'system' speed, < user speed w/1s lead-in.
# > and < are not displayed. << will add silent 2s delay.
# Example:  
#   >System Prompt: <Login monkey
#   >Password: <mypasswordis1234
#   >LOGIN FAILED
# Note: Unix sleep used to delay less than 1 second
# 2016 @garyd @diemastermonkey for DronesoundTV

my $Delay;
my $DelayRange = 0.15;	      # Delay tiny as sfx now delays enough
my $SFX = "./sfxKeystroke";   # Makes a single clickity sound
my $Human = 0;                # True when 'human typing'

$In = shift (@ARGV) or die ("\nUsage:\n\t$0 InputFile");
open (IN, "<$In") or die ("\nCant open $In");

while (! eof(IN)) {
  $Char = getc (IN);
  if ($Char eq '>') { $Human = 0; $DelayRange = 0; next;} 
  if ($Char eq '<') { $Human = 1; $DelayRange = 0.2; `sleep 0.3`; next;}

  `$SFX` if ($Human == 1);  # Human type sfx
  print ($Char);

  if ($DelayRange) { 
    $Delay = 0.01 + rand($DelayRange);
    `/bin/sleep $Delay`;
  }
}
close (IN);
# fin
