#!/bin/sh
# Crude startup script for DronesoundTV / StageGhost
# Almost no error checking
# 2016 @garyd @diemastermonkey

cd /pub/kits/sonicmonkeypi

# Panel Server first, at least UI up
./PanelServer-startup &

# Start YouTube OAuth Token Maintenance Loop
# Start YouTube Chat Polling Loop
./ytTools-startup &

# Start DroneTV Sound kludge loop UNLESS API token empty
TOKEN=`cat config/dronetv.freesoundtoken | xargs`
MSG="NOT Starting Dronesound Engine, because no config/dronetv.freesoundtoken"
if ! test -z "$TOKEN"; then
  ./DroneTV-kludgeloop &> /dev/null &
  MSG="Starting Dronesound Engine..."
fi
echo "$MSG"

# Start "Attract Mode"
./AttractMode &> /dev/null &

# Retired: Start Onboard Synth
# ./synthLoop &> /dev/null &

# Retired: Setup Raspberry Pi GPIO
# sudo ./uiFlashSetup &

echo " "
echo " Reminder, run"
echo " "
echo "              ./DronesoundTV"
echo " "
echo " ...to start the lo-fi animations."
echo " "

# echo " "
# echo " RUNNING CHANNEL HELLO WITH MUSIC! "
# echo " "
# ./DroneTV-hello
