#!/usr/bin/perl
# Get any current bpm, pick a track, call the sample player in patterns
# Example mixdown with repeat beat Note: With 'play', will play at same time!
# play -m in.wav ../dmm/DMM_Selection202_Excerpt.wav out.wav fade 3 0 3 trim 40 5.3 repeat 3
# sox -m (...)

# Pick a drum sample, get latest known 'drone' BPM
@list = `ls -1 dmm/*.wav`;   
$Track = @list [int(rand(scalar(@list)))];
chomp ($Track);
$BPM = `/usr/bin/perl bbGetBPM`; chomp ($BPM);
$BPM = `cat beatbot.bpm`; chomp ($BPM);
if ($BPM < 20) { $BPM = 20; }
$Beat = 60 / $BPM;		# Beats per second ie rate
$Half = $Beat * 2;    # Half measure
$Measure = $Half * 2; # Full measure
$Triplet = $Beat * 3;

# Use the latest available 'excerpt' 
$Excerpt = "remix/excerpt.wav";

# Offset into sample MUST be LTE sample duration
# Altoff, etc are other start points
$Offset = int(rand(120) + 30);			# Make size of input
$HalfOff = $Offset + $Half;   # Startpos + half measure
$FarOff =$Offset + $Measure; # One full measure ahead

# RATE=`perl -e 'print rand(0.15)+0.60;'`
# Not even max rate is quite slow
$Rate = rand(0.40) + 0.60;	
# Rarely, double it
$Rate =	$Rate * 2 if (int(rand(5) == 0));

# sh bbPhrase $TRACK $OFFSET $BEAT $RATE

# Make the track
$Ignored = `/usr/bin/sox -v 1.1 -m $Track $Excerpt remix/beat.wav trim $Offset $Measure speed $Rate repeat 2`;
$Ignored = `/usr/bin/sox -v 1.1 -m $Track $Excerpt remix/reverse.wav trim $Offset $Measure speed $Rate reverse`;

# Touch a file to indicate beats in progress
$Ingored = `/usr/bin/touch BeatBot.active`;

# Play track sequence a few times
# First fade it in
$Ignored = `/usr/bin/play -V0 -q remix/beat.wav fade 3 0 0`;
$Ignored = `/usr/bin/play -V0 -q remix/reverse.wav`;
for ($i=0; $i < 2; $i++) {
  $Ignored = `/usr/bin/play -V0 -q remix/beat.wav`;
  # Play reverse half of time
  if (int(rand(2)) == 0) {
    if (int(rand(2)) == 0) {   # kludge
      $Ignored = `/usr/bin/play -V0 -q remix/reverse.wav reverb`;
    } else { 
      $Ignored = `/usr/bin/play -V0 -q remix/reverse.wav speed 2 repeat 1`;
    }
  } else {
    sleep($Measure);   # or silent measure
  }
}
# Finally, play with a fade out
$Ignored = `/usr/bin/play -V0 -q remix/beat.wav repeat 3 fade 0 0 5`;

# Remove the 'active' file
$Ingored = `/bin/rm BeatBot.active`;

