#!/usr/bin/python3

import http.server
 
# import BaseHTTPServer
# import CGIHTTPServer
import cgitb; cgitb.enable()  ## This line enables CGI error reporting
 
# server = BaseHTTPServer.HTTPServer
# handler = CGIHTTPServer.CGIHTTPRequestHandler
server = http.server.HTTPServer
handler = http.server.CGIHTTPRequestHandler
server_address = ("", 8000)
# handler.cgi_directories = ["cgi"]
 
httpd = server(server_address, handler)
httpd.serve_forever()

