#!/bin/sh
# Simply play a few synth pads of current frequency
# from DroneTV.pitch

while (true); 
  # Play 10s notes, repeat 2 (total 3 plays)
  # To do: append fx
  do ./synthOnboard $((`cat DroneTV.pitch` % 80)) 10 2 &> /dev/null; 
  # To do: Make sleep time match .bpm file
  sleep 30; 
done
