#!/usr/bin/perl
# Simple synth w/SOX for DronesoundTV
# Creates 10s files for each freq as needed
# or plays existing, with args/fx, fixed 25 pct fade in/out
# 2016 @diemastermonkey @garyd

# Handle args/usage
my ($Freq, $Len, $Repeats, $FX) = @ARGV 
  or die ("Usage:\n\t$0 <Freq> <Length> <Repeats> "
    ." [Manual_SOX_FX_Args]\n\n");
my $Fade = $Len * 0.48;

# Create base freq wave file if not exist
unless (-r "synth/$Freq.wav") {
  $R = `sox -V0 -q -d synth/$Freq.wav synth sine $Freq trim 0 15`;
}

# Play as per args, also output syntax for pipes
$S = "play -V0 -q synth/$Freq.wav trim 0 $Len "
  ."vol 0.75 fade $Fade 0 $Fade $FX repeat $Repeats";
# print ("\n$0: $S");
$R = `$S`;
# Fin
