#!/bin/sh
# Just keep refreshing OAuth tokens
# Note json response to request in ytRefreshTokens
# gives best interval time (typically 3600 seconds)
# though its hardwired here. -dmm
cd /pub/kits/sonicmonkeypi
./ytRefreshTokens
sleep 5
while (true); do ./ytRefreshTokens &> /dev/null ; sleep 3600; done
