#!/bin/sh
# Accept 6-char RGB for panel background color
# New: 'random' option randomizes from config/sg.colors
# @garyd @diemastermonkey 2017

# Theme ie relative path for output
THEME=`cat PanelServer.theme | xargs`
# Random color if desired
RANDOMCOLOR=`cat config/sg.colors | sort --random-sort |  tail -1`;

# Give help and exit if no arg
if test -z "$1" ; then
  CURRENT=`cat themes/$THEME/PanelServer.rgb | xargs`
  echo "COLOR sets the background (or other parts) to an RGB color value. Now, it is $CURRENT. Pick another at http://colorpicker.com, then use COLOR RgbValue. Also try COLOR random"
  exit
fi

# Clean up args
CLEAN=`echo "$1" | perl -ne 's/#//g; print;' | xargs`

# If 'random', set random color but drop-through to normal handling
if test $CLEAN = "random"; then
  CLEAN=$RANDOMCOLOR
fi

# Respond with a censored version
echo "Ooh, new COLOR - thanks! Remember there is a stream delay, k?"

# Else simply sanify it and put it in rgb
echo "$CLEAN" > themes/$THEME/PanelServer.rgb
