#!/bin/sh
# WEIRD! This string is cursed! Srsly try posting it via MessageInsert!
# echo "New? Welcome! Type COMMANDS for lots to do, SUB for the sub bot."
echo "New? Welcome! Type COMMANDS for lots to do. Try GAMES, too!"
