#!/bin/sh
# Simply list user commands but not symlinks or hidden 
# .files - that allows aliases and secret commands. 
# 2016 @garyd @diemastermonkey for DronesoundTV

LIST=`find commands/* -type f | sed "s/commands//" | sed 's/\///' | xargs | sed 's/ /\, /g'`
echo "[Commands] Commands include: $LIST"
# Fin
