#!/bin/sh
# Simple example StageGhost user command
# Write the numeric argument to a file


# Give help and exit if no arg
if test -z "$1" ; then
  FILT=`cat DroneTV.filter | perl -ne 'chomp; print $_;'`
  echo "[Filter] Adjusts the low-pass filter frequency (currently $FILT hz). Usage: FILTER FrequencyHz"
  exit
fi

echo "$1" > config/dronentv.filter
CLEAN=`echo $1 | sed "s/[abcdefghijklmnopqrstuvwxyz_]//g"`
echo "[Filter] Low-pass filter adjusted to $CLEAN hz."
