#!/usr/bin/perl
# StageGhost: Example simple random witty response
# 2016 @diemastermonkey For DronesoundTV

# Random responses, one per line
# Remember to end sentences, text might be added.
@Answers = split (/\n/, 
"Insert witty response here.
Hi!
Hello!
Hi, new here?
Hello.
Haaroooo!
How do you doooooooo?
Greetings.
Greetings, programs.
Hi!
Hello!
Hi, new here?
Hello.
Haaroooo!
How do you doooooooo?
Greetings.
Greetings, programs.
Cooooooool.
Bonjour!
Hola!
Guten Tag!
Ciao!
Ola!
Namaste.
Salaam.
Zdras-Tvuy-Te.
Ohayo!
Konban Wa.
Ahn-Young-Ha-Se-Yo?
Merhaba!
Szia!
Marhaba!
Sannu.
Habari!
Ni Hau!
nuqneH!
tlhIngan!
Hi there.");

# Pick a response
$Answer = @Answers[rand(scalar(@Answers))];  # For text
chomp ($Answer);
$Speak = $Answer;                            # For speech

# Often append help blurb
# if (0 == int(rand(2))) {
  $Answer .= " Type HELP for basics, COMMANDS or RTFM for more.";
# }

# Rarely, rickroll :)
if (0 == int(rand(3))) {
  $Answer .= " Psst! Secret Power User Vid at https://youtube.com/watch?v=VzuDnbjIhbg";
}

# Output to chat and voice
# Tip: Do long work first, as text will lead stream anyways!
$Ignore = `echo "$Speak" | /usr/bin/festival --tts &`;  # Short
print ("[DroneBot] $Answer");                           # Long

# Fin


