#!/usr/bin/perl
# A stupid hidden commands to play hilarious "Janitor Story" interview
# Freesound ID 165241 by Corsica_S - because I love it so much. :) -DMM

# Random responses, one per line
my @Answers = split (/\n/,
"Twenty bucks! Twenty bucks!
Twenty bucks! Twenty bucks!
Hey man...buyer beware.
Oh, totally.
What, wadda you want??
Im busy Im trying to work!
Gene Simmons KISS boots. And nothing else.
But, we wanna buy donuts.
We want to buy donuts!
You guys are harrasing him, you gotta pay twenty bucks.
He would clean...nude.
He would clean nude!?
Naked. Naked.");
# Select one randomly
my $Answer = @Answers[int(rand(scalar(@Answers)))];

# To chat
print ("[Janitor] $Answer");

# Queue up The Janitor Story!
`./DroneTV 1 =165241 Request >> log.txt &`
