#!/usr/bin/perl
# 
# Simple backend-and-chat to frontend conduit for PanelServer
# for DTV 

# Settings
my $sQueueFile = "conduit.queue";

# Pre-processing

# Default (no parms request) response: Serve latest message from queue
open (IN, "<$sQueueFile") or die;
@Queue = <IN>;
close (IN);

$msg = shift (@Queue)
  or $msg = "none";

# Update queue
open (OUT, ">$sQueueFile") or die;
print (OUT @Queue);
close (OUT);

# Output
# Mandatory http header
print ("Content-type: text/html\n\n");
print ($msg);


