#!/usr/bin/perl
# Simple oauthcallback handler (see ytAuthInit)
# Writes to config/sg.yttemptoken for immediate use by ytValidateTokens
# @garyd @diemastermonkey 20170115

# Outfile is http server relative
my $Outfile = "/config/sg.yttemptoken";
my $AfterPage = "/cgi-bin/setup";    # Send user here after
my $Query = $ENV{'QUERY_STRING'};

# Mandatory http header
print ("Content-type: text/html\n\n<!DOCTYPE html>\n");
print ("<head>\n");
# Insert javascript here if desired
print ("</head>\n");

# On fail
unless ($Query) {
  print ("No data received, sorry.");
  print ("<br>Return to <a href='$AfterPage'>Setup Page</a><br>");
  print ("</body>\n"); print ("</html>");
  die;
}

# On success
print ("Thank you, access configured.");
print ("<br>Return to <a href='$AfterPage'>Setup Page</a><br>");
print ("</body>\n"); print ("</html>");

# Update files
$Query =~ s/code=//gi;         # Cleanup
open (OUT, ">$Outfile") or die; print (OUT $Query); close (OUT);
open (OUT, ">$0.debug") or die; print (OUT $Query); close (OUT);
