#!/usr/bin/perl
# Primitive setup UI for DronesoundTV/Stageghost
# 20161121 @garyd @diemastermonkey
# Reminder: %ENV contains other handy info

# Globals
my $Empty;		   # Empty config fields
my $Dash = "-" x 48;
my %Config;
my $sQuery = $ENV{'QUERY_STRING'};
my @CGI = split (/\&/, $sQuery);
my $sURL = "/cgi-bin/setup"; # Path to cgi
my $ConfigPath = "config"; # Subdir for settings files
# Get pre-generated approval url per settings
my $AuthInit = `./ytAuthInit`; chomp ($AuthInit);

# Onboard logs for 'fnSummaryLogs'
my $sLogSummary;
my @Logs = (
  "ytCheck-chat.log", "ytCheck.processed", "ytCheck.debug", "ytCheck.log",
  "ytSinglePost.log", 
  "ytMessageDelete.log", "ytCheapBan.log",
  "ytUserInfo-raw.log", "ytUserSubscribe.debug", "ytModifyBroadcast.debug",
  # Disused # "ytValidateTokens.debug",
  "PanelServer.log", "PanelServer-raw.log", "PanelServerRefresh.debug",
  "remix.queue", "remix.debug",                 # jukebox stuff
  "log.txt", "DroneTV.debug", "DroneTV.creds"   # Dronesound stuff
);

# Mandatory http header
print ("Content-type: text/html\n\n");
# print ("<!DOCTYPE html>\n");  # Bad form now?
print ("<html>\n");
print ("<head>\n");
fnWebScript();		# Script must go in header
print ("</head>\n");
print ("<body>\n");

# UI
fnWebPrintln ("Using $0 <hr>");
fnWebForm();     # Display form

# CGI: update fields if exist (supports multiple, only one used)
foreach $Line (@CGI) {              # Parse CGI to Data hash
  ($Field, $Value) = split (/\=/, $Line);
  fnConfigWrite ($Field, $Value);   # Update only if exists
}

# Get/display saved config
fnConfigRead();

# Edit field for display and edit
print ("
  <input type=\"text\" 
    onChange=\"fnEditValue();\"
    autofocus='autofocus' 
    id=\"uiTextOut\" size=\"48\">
  <br><br>"
);

# Start the select list
fnWebPrintln (
  "<select id='fieldSelect' "
  # . "autofocus='autofocus' "
  . "onChange='fnUpdateValueDisplay();'"
  . "DISABLED_onFocus='fnHideValueDisplay();'"  # Broken
  . "DISABLED_onInput='fnShowValueDisplay();'"
  . "> "
);  

# Make list option for each key (field name)
foreach $Line (sort(keys(%Config))) {
  fnWebPrintln ("<option>"
    . $Prefix . $Line         # Just name of field
    . "</option>"
  );
}
# Extra (invalid) default
fnWebPrintln ("<option selected value=''>Select...</option>");
fnWebPrintln ("</select>");   # End select list

# Also, hidden fields with the values, named with field name
foreach $Line (sort(keys(%Config))) {     # PS sort superfluous
  fnWebPrintln (
    "<input type=\"hidden\" id=$Line value=\""
    . substr($Config{$Line}, 0, 96) 
    . "\">"
  );
}

# Bottom: Note empty config fields, if any
if ($Empty) {
  fnWebPrintln (
    "<div id='uiNotice' class='uiNotice'>"
    . "<br>Note: The following settings are empty: "
    . $Empty . "<br>"
    . "</div>"
  );
}

# Display AuthInit output only if key config items empty
if (length ($Config{'sg.yttemptoken'}) == 0) {
  # Webify ytAuthInit output meant for console
  $AuthInit =~ s/\n/<br>/gmo; 
  $AuthInit =~ s/(https.*$)/<a href='$1'>$1<\/a>/g;
  fnWebPrintln (
    "<br><div id='authint' class='authini'>"
    . "<b>Note</b>: "
    . "Authentication might not be set up...<br>"
    . $AuthInit 
    . "</div>");
}

# Diag logs
fnLogSummary();
fnWebPrintln (
  "<div id='uiLogs' class='uiLogs'>"
  . "<br>Log Summary: <hr> "
  . "<pre>"
  . $sLogSummary . "<br>"
  . "</pre>"
  . "</div>"
);

# Close the HTML!
print ("\n</body></html>");

# Functions
# ----------------------

# Print one line webishly
sub fnWebPrintln {
  print ("\n".shift(@_));
}

# Spit out webform
sub fnWebForm {
  # Print until END
  print 
<<END
  <form action="$sURL">
    Configuration 
    <input type="submit" id="submit" value="Submit"> <br>
    $Dash
    <!-- Store single field/value update till submit   -->
    <input type="hidden" id="update" name="" value="">
  </form>
  <br>
END
}  # End function

# Print javascript into the html header
sub fnWebScript {
  # Print until END
  print 
<<END
  <script type="text/javascript">

    function fnUpdateValueDisplay () {
      var sField = document.getElementById('fieldSelect').value;
      var sValue = document.getElementById(sField).value;
      document.getElementById('uiTextOut').value = sValue; // Display 
    }

    // To do: Combine into generic 'hide/show this' fn
    function fnShowValueDisplay () {   
      document.getElementById('uiTextOut').style = "display:block;";
    }

    function fnHideValueDisplay () {   // When select opened
      document.getElementById('uiTextOut').style = "display:none;";
    }

    // When displayed value edited, update hidden update field
    function fnEditValue () {
      var sField = document.getElementById('fieldSelect').value;
      var sValue = document.getElementById('uiTextOut').value;
      // Update visually
      document.getElementById('uiTextOut').value = sValue;
      // Set hidden field name/value to update data
      document.getElementById('update').name = sField;
      document.getElementById('update').value = sValue;
    }
  </script>
END
}

# Get all existing config data, via fnConfigGet 
sub fnConfigRead {
  foreach $setting (`find $ConfigPath/ -type f`) {
    $setting =~ s/$ConfigPath\///g;  # Remove path
    chomp ($setting);

    $Config{$setting} = fnConfigGet($setting); # Store value to hash
    # Add to (global!) 'empty' list for reporting only
    $Empty .= "$setting " unless (length($Config{$setting}));
  }
}

# Simple, cheap, safe config file reader
# Read a single value from a single thus-named file
# Use a naming convention to support multi-user/session
# Returns value or empty (q: what if value 'empty'?)
# Example use:
#   $Config{'DuckVolume'} = fnConfigGet ("dronetv.duckvolume");
# -----------------------------------------------------
sub fnConfigGet {
  my $argFieldName = shift (@_) or return;
  open (IN, "<config/$argFieldName") or return;
  my @in = <IN>;        # Slurp all
  close (IN);
  $out = join ("\n", @in);

  # Remove comments, blanks, limit to single line of data
  $out =~ s/^#.*\n*$//gmo;
  $out =~ s/^\s*$//gmo;
  $out =~ s/\n|\r//gmo;

  return ($out);
}


# Update an existing config data file (MUST pre-exist)
sub fnConfigWrite {
  my $f = shift (@_);  # field/value
  my $v = shift (@_);

  if (-w -f "$ConfigPath/$f") {
    open (OUT, ">$ConfigPath/$f") 
      or return();	# No err reporting!  
    print (OUT $v);
    close (OUT);
  }
}    

# Summarize logs for diags
sub fnLogSummary {
  my $rawlog;
  my $iLogLen = 10;
  $sLogSummary .= "\n # Status # \n"   # Beware hardwired path
     . $Dash . "\n"
     . `commands/status` . "\n"; 
  foreach $Log (@Logs) {
    $sLogSummary .= "\n # $Log # \n"
      . "-" x 40 . "\n"
      . `tail -$iLogLen $Log` . "\n"
      . "-" x 40 . "\n";   
  }
}

# Fin

